In [1]:
import duckdb

In [2]:
con = duckdb.connect(database='dados_duckdb.db', read_only=False)

In [4]:
df = con.execute('SELECT * FROM silver_produtos').fetchdf()
df.head(10)

      id nm_produto id_categoria  id_fornecedor  vl_preco
0  10001   PARAFUSO         BT10            100     100.0
1  10002    MARTELO         BT50            100    1500.0
2  10004      SERRA         BT50            100     200.0
3  10005    MACHADO         BT50            100     200.0
4  10003      PREGO         BT10            100      60.0

In [6]:
df2 = df.drop(columns=['id_categoria','id_fornecedor'])
df2.head(10)

      id nm_produto  vl_preco
0  10001   PARAFUSO     100.0
1  10002    MARTELO    1500.0
2  10004      SERRA     200.0
3  10005    MACHADO     200.0
4  10003      PREGO      60.0

In [7]:
con.execute('''
CREATE TABLE IF NOT EXISTS dim_produtos (
            id BIGINT,
            nm_produto TEXT,
            vl_preco FLOAT
            )
''')

In [8]:
con.execute('INSERT INTO dim_produtos SELECT * FROM df2')

In [9]:
df_dim = con.execute('SELECT * FROM dim_produtos').fetchdf()
df_dim.head(10)

      id nm_produto  vl_preco
0  10001   PARAFUSO     100.0
1  10002    MARTELO    1500.0
2  10004      SERRA     200.0
3  10005    MACHADO     200.0
4  10003      PREGO      60.0

In [10]:
con.close()